# Spring
spring:
  application:
    name: gateway
  security:
    user:
      name: user
      password: user
# Server
server:
  port: 8080
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
